### ISSUE TITLE
how to obtain cell specificity CTCF motif file with direction info

### ISSUE THREAD

**Issue by usernicai** [dozmorovlab/PDXHiC_supplemental#3]
How to get the hg38 CTCF fimo.bed file used in the script Fig6_HiC_Loops/04_CTCF_Orientation.sh？ Is it similar to get CTCF_hg38_all. bed  following instructions in https://dozmorovlab.github.io/CTCF/ ? If i have my own CTCF ChIP - seq data,  how to obtain cell specificity CTCF motif file with direction info, Do i just need to intersect with the motif file in the reference database?

**Comment by mdozmorov** [comment]
`fimo.bed` is now a part of the repository
