### ISSUE TITLE
allEnrichments.tsv used in Fig7_HiC_Enrichments/05_UniBind_Plots.Rmd

### ISSUE THREAD

**Issue by usernicai** [dozmorovlab/PDXHiC_supplemental#4]
HELLO,how to get the allEnrichments.tsv used in Fig7_HiC_Enrichments/05_UniBind_Plots.Rmd ,I see no UniBind differential analysis result on masked CR loop anchors vs. masked PR loop anchors produced by 04a_Anchor_Masking.Rmd,many thxs!

**Comment by mdozmorov** [comment]
It is now committed.

**Comment by usernicai** [comment]
THX，so  how to get this file since i've got my own loop and anchor file,I truly want konw the method,not just the result that acts like a black box,it would be of great of help if you could provide the corresponding code chunk or the detailed process,many THX!
